# Generated by Django 6.0.5 on 2026-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
